version: '2'
services:
  postgres:
    image: postgres:13
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5555:5432